/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.meshydb;

/**
 * Class for Meshy Client.
 */
public class MeshyClient {
   /**
   * Test Method for library.
   * @return  dummy value
   */
    public boolean someLibraryMethod() {
        return true;
    }
}
