/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.meshydb;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MeshyClientTest {
    @Test void testSomeLibraryMethod() {
        MeshyClient classUnderTest = new MeshyClient();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
